name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        cd api
        npm install
        cd ../frontend
        npm install

    - name: Test Python Script
      run: |
        cd api
        python -m unittest discover

    - name: Test ReactJS Frontend
      run: |
        cd frontend
        npm test

    - name: Build Docker Images
      run: |
        docker build -t myapp/api ./api
        docker build -t myapp/frontend ./frontend

    - name: Push Docker Images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          myapp/api:latest
          myapp/frontend:latest

    - name:

