name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          cd api
          npm install
          cd ../frontend
          npm install

      - name: Build Docker images
        run: |
          docker build -t dev/api:latest ./api
          docker build -t dev/frontend:latest ./frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Test backend code
        run: |
          cd api
          npm test

      - name: Test frontend code
        run: |
          cd frontend
          npm test

      - name: Deploy application
        run: |
          cd api
          npm run build
          cd ../frontend
          npm run build
          
          # Here you can add the steps to deploy the application to your on-premises environment
          # For example, you can use SCP or some other tool to copy the files to the server

